# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
minimal_mistakes_skin    : "default" # Options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Mahan Tafreshipour"
title_separator          : "-"
description              : "Mahan Tafreshipour Portfolio"
url                      : "https://mahantaf.github.io" # Ensure this is correct
baseurl                  : "" # Set to "/" if deploying to GitHub Pages
repository               : "mahantaf/mahantaf.github.io"
# logo                     : "/assets/images/avatar.jpg" # Ensure avatar exists

# Navigation Bar
header_pages:
  - index.md
  - about.md
  - projects.md
  - blog.md
  - contact.md

# Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mtafreshipour"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mahantaf"
    - label: "Feed"
      icon: "fas fa-fw fa-rss"
      url: "/feed.xml"

# Author Information
author:
  name             : "Mahan Tafreshipour"
  avatar           : "/assets/images/avatar.jpg"
  bio              : "Computer Science Ph.D. student at UC Irvine"
  location         : "California, Irvine, USA"
  email            : "mtafrsh@uci.edu"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:mtafrsh@uci.edu"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mahantaf.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mtafreshipour"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mahantaf"

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Styling: Make Fonts Smaller
sass:
  sass_dir: _sass
  style: compressed

# Custom CSS
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Markdown Processing
markdown: kramdown
highlighter: rouge
